<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilih_product</name>
   <tag></tag>
   <elementGuidId>d27217b1-178a-40b8-b528-e77c18da008c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-select-placeholder.text-muted.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acf416d6-522f-4e52-bb4b-a301e320dcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>$select.isEmpty()</value>
      <webElementGuid>4804f554-0c85-4ea3-af43-eded5c8b9972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-select-placeholder text-muted ng-binding</value>
      <webElementGuid>6ac4e8f6-428a-43b8-95da-5ba5e5fabf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'focused': $select.focus }</value>
      <webElementGuid>a40feedf-2a74-46bc-9fb2-c5b0812c5fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;body_ custom zoomed_del browser- theme-grey&quot;]/div[2]/layout-manager[@class=&quot;custom ng-isolate-scope&quot;]/div[@class=&quot;main-panel&quot;]/layout[@class=&quot;layout-frame ng-scope ng-isolate-scope active-frame&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;panel animate pane_ContractApplSetProductNonTop  label-warning id_11 last&quot;]/tab[@class=&quot;custom_tab_1 tab-container&quot;]/div[@class=&quot;tab has-sub-tab package-WSCards_APPLICATION_MANAGEMENT   tab-form&quot;]/div[@class=&quot;tab-content tab-without-links has-not-top-links&quot;]/div[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;form-container-outer&quot;]/form[@class=&quot;content-element ng-pristine vertical-layout ng-invalid ng-invalid-ui-select-required-validator&quot;]/div[@class=&quot;inner inner-x ng-scope hovered inner-visible&quot;]/div[@class=&quot;form-container form-sub&quot;]/div[@class=&quot;first-group ng-scope&quot;]/div[@class=&quot;field-block-container&quot;]/field-block[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-field field_code_Product required&quot;]/div[@class=&quot;form-value&quot;]/field[@class=&quot;field-value ng-isolate-scope&quot;]/select-full[@class=&quot;field ng-scope ng-isolate-scope&quot;]/div[@class=&quot;select select-full&quot;]/div[@class=&quot;select-place text-edit ui-select-container ui-select-bootstrap dropdown ng-empty ng-invalid ng-invalid-ui-select-required-validator ng-touched&quot;]/div[@class=&quot;ui-select-match ng-scope&quot;]/div[@class=&quot;ui-select-scope ui-select-toggle&quot;]/div[@class=&quot;ui-select-placeholder text-muted ng-binding&quot;]</value>
      <webElementGuid>08d2e37b-028d-4bd0-9413-592666be4d02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[6]</value>
      <webElementGuid>cd3bab8b-3fa0-4abb-96af-4bd84fa0862a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[3]/following::div[7]</value>
      <webElementGuid>ff89209c-2582-4514-82c3-6bf8e72d9f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empty'])[1]/preceding::div[4]</value>
      <webElementGuid>893cdacb-73de-42e7-a689-d34355598100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='loading...'])[1]/preceding::div[4]</value>
      <webElementGuid>9505ca53-b724-4ab4-bd11-f466fcea8bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select-full/div/div/div/div/div</value>
      <webElementGuid>5bbbfed2-59d8-462b-92f2-31d4964d2755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
