<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>baris_kedua</name>
   <tag></tag>
   <elementGuidId>8988db80-0b6a-4860-abaa-08712c69a963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-widget-content.slick-row.odd > div.slick-cell.l1.r1 > span.cell-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gridElement']/div[5]/div/div[2]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e08e3470-1d8d-4889-ad2b-12c32dedd2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>43f2715e-4355-4f9e-93c0-bb5be957366d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>40792909928900-02893</value>
      <webElementGuid>3cb18b75-75d2-46c7-872c-b686e512b182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell-content</value>
      <webElementGuid>f178a7d3-f64b-49a8-b40d-1b2ed5870719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>40792909928900-02893</value>
      <webElementGuid>5fc0c0f0-1536-4839-bcd1-937f1c245b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;body_ custom zoomed_del browser- theme-grey&quot;]/div[2]/layout-manager[@class=&quot;custom ng-isolate-scope&quot;]/div[@class=&quot;main-panel&quot;]/layout[@class=&quot;layout-frame ng-scope ng-isolate-scope active-frame&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;panel animate pane_NodeApplClassifierListClassifiersGetAll_ContractApplClassifiers   id_10 last&quot;]/tab[@class=&quot;custom_tab_2 tab-container&quot;]/div[@class=&quot;tab has-sub-tab package-WSCards_APPLICATION_MANAGEMENT   tab-focused&quot;]/div[@class=&quot;tab-content has-top-links&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;grid-container&quot;]/div[@id=&quot;gridElement&quot;]/div[@class=&quot;slick-viewport&quot;]/div[@class=&quot;grid-canvas&quot;]/div[@class=&quot;ui-widget-content slick-row odd&quot;]/div[@class=&quot;slick-cell l1 r1&quot;]/span[@class=&quot;cell-content&quot;]</value>
      <webElementGuid>dffb0004-5e61-4555-b9e2-95dba594d76c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridElement']/div[5]/div/div[2]/div[2]/span</value>
      <webElementGuid>4b425cb4-5d1e-4220-b5a2-63ee19a6fa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::span[2]</value>
      <webElementGuid>72e71e78-f18d-49dd-a25c-b38c97a61bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Date'])[1]/following::span[12]</value>
      <webElementGuid>9f2a050c-315f-4676-b31f-6a8e85e48969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add or Update'])[2]/preceding::span[3]</value>
      <webElementGuid>861211ae-5d53-4008-a35f-e3f8ed1f67cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card Autopay Method'])[1]/preceding::span[6]</value>
      <webElementGuid>ee2fd911-1c83-4f5d-b1a1-cf07704a95cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='40792909928900-02893']/parent::*</value>
      <webElementGuid>8907ab84-3c35-49f4-9575-a0dfc884c907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/span</value>
      <webElementGuid>c8f9705b-17f9-4b98-b8a7-37f1634742ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '40792909928900-02893' and (text() = '40792909928900-02893' or . = '40792909928900-02893')]</value>
      <webElementGuid>a41b0442-95d0-4dc9-9189-bdd805397858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
