<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Invalid login or password</name>
   <tag></tag>
   <elementGuidId>6f418e2b-aac4-4c69-9ead-8522a65671ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-message-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='login-message-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>62210d37-90ea-4a4e-ad4e-49f93c33a4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-message-text</value>
      <webElementGuid>e27446e6-10e6-428f-b7a9-d1ae18a9cb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>message | translate</value>
      <webElementGuid>8031e232-4020-44c8-8b1a-4258420ba201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>message != undefined</value>
      <webElementGuid>15d42df4-0165-4d9b-9356-db1f24f90977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>78e184fe-6a75-49b3-b444-1212c514b19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid login or password</value>
      <webElementGuid>0f6c9c0b-c566-4206-a3f2-36e3e36ed936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-message-text&quot;)</value>
      <webElementGuid>a8b77991-23fb-4b94-a6d8-ae1d7a434843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='login-message-text']</value>
      <webElementGuid>57032d88-a2d6-40b1-9697-d66c8e800e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::span[6]</value>
      <webElementGuid>e6823bde-9879-42c1-854d-38c3656858cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[9]</value>
      <webElementGuid>bd6f3cd2-080a-4fdc-8415-c1f6e8345055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change your password?'])[1]/preceding::span[1]</value>
      <webElementGuid>0391376e-9212-4928-96a4-bfce554860f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::span[1]</value>
      <webElementGuid>c4c5c9bd-0cbd-4b10-83ff-8b2ec66a1f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid login or password']/parent::*</value>
      <webElementGuid>adb28148-1aaa-467f-8983-fd3f87f6c1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>bc7ba8de-b170-48f4-a80e-5f29d53ba74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'login-message-text' and (text() = 'Invalid login or password' or . = 'Invalid login or password')]</value>
      <webElementGuid>c28da2de-f016-4ea8-8e08-494a6ce38853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
