<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_English_svg</name>
   <tag></tag>
   <elementGuidId>b138df48-ea99-4202-83a8-51d9dc9bb51c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-message-icon > span.block-svg > svg.svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid login or password'])[1]/preceding::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>1fbb250a-77df-4854-a336-dcf5e6ff1ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f93223f1-1978-4c43-8c92-7586e539f93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{ 'width' : ctrl.width, 'height' : ctrl.height, 'fill': ctrl.color}</value>
      <webElementGuid>8df5220d-5659-4f44-ac9b-db96ad25c972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'svg-green': ctrl.color == 'green'}</value>
      <webElementGuid>3fee3467-0319-4e4b-b076-3089fcd3de42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7efeb38d-af15-444e-bca1-f9c5aa806cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-message-icon&quot;)/span[@class=&quot;block-svg&quot;]/svg[@class=&quot;svg&quot;]</value>
      <webElementGuid>6b6281a9-9a21-40cb-b88c-1e1581a458a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>b4a9d1b5-3d7d-4572-9d41-87d4712220e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>10102875-7896-4ae4-a047-ee20cf9daee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid login or password'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>a4244eb6-925d-4ef3-8d97-090b3a01532f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change your password?'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>fa61a369-fb61-49d5-a3da-06a1a2183c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
