<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name_issuing_client</name>
   <tag></tag>
   <elementGuidId>7850f8a1-e11d-4daf-abb5-a88235f72fee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Display']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Display&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39236168-7eff-443d-b2ec-a3488d500b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63ffad9d-edc2-4d0e-9cea-c922b944cab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b8a6d37d-7ea9-49b5-9acb-5c6fd67a46e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-edit use-rtl ng-pristine ng-empty ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-check-spaces ng-touched</value>
      <webElementGuid>04eeeab2-988d-43d4-93ad-6f14da006b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'align-right': isNumber}</value>
      <webElementGuid>c3d8ff5f-fc0b-4d4c-ad27-923fb0788749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Display</value>
      <webElementGuid>f69a2d91-c545-4034-b646-4ff2d319784d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model.masked_value</value>
      <webElementGuid>a7b27376-44ea-4700-8a68-20772a655868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>req</value>
      <webElementGuid>46857f13-2b6e-4b2b-98f4-e97251757bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f16933aa-7660-476a-98ee-4afba8c6f660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-maxlength</name>
      <type>Main</type>
      <value>{{maxLength}}</value>
      <webElementGuid>333467c0-f4c5-4c3b-9afe-42ff17bd5e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>character-case</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>7ef4e8a0-05ea-4a7b-ab7c-323641693b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-trim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf27b405-9a0b-40f9-a967-2d53fa5a81c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>applyChanges()</value>
      <webElementGuid>2559077e-d08a-4723-9eb5-e6a05a00f50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>applyChanges()</value>
      <webElementGuid>af946e00-081d-4dfd-948a-89d076be647c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>87c76a1d-1585-4392-8b2b-0e095f5fd99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6165c693-8557-48b2-b8df-4fbf73251731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;body_ custom zoomed_del browser- theme-grey&quot;]/div[2]/layout-manager[@class=&quot;custom ng-isolate-scope&quot;]/layout[@class=&quot;layout-modal ng-scope ng-isolate-scope&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;panel animate pane_Apply no-header  id_7 last first&quot;]/tab[@class=&quot;custom_tab_0 tab-container&quot;]/div[@class=&quot;tab has-sub-tab package-WSCards_APPLICATION_MANAGEMENT   tab-focused&quot;]/div[@class=&quot;query-form-wrapper&quot;]/div[@class=&quot;query-form-container ng-scope hovered&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;query-form&quot;]/form[@class=&quot;content-element ng-pristine readonly vertical-layout ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-check-spaces&quot;]/div[@class=&quot;form-container form-field-count-1&quot;]/field-block[@class=&quot;ng-scope first&quot;]/div[@class=&quot;form-field field_code_Display required&quot;]/div[@class=&quot;form-value&quot;]/field[@class=&quot;field-value ng-isolate-scope&quot;]/text-field[@class=&quot;field ng-scope ng-isolate-scope&quot;]/input[@class=&quot;text-edit use-rtl ng-pristine ng-empty ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-check-spaces ng-touched&quot;]</value>
      <webElementGuid>c2aec70a-050a-4832-90c7-1b3494b10637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Display']</value>
      <webElementGuid>15ea9de3-f2ce-40ef-b5a9-236ea7802ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/field-block/div/div[2]/field/text-field/input</value>
      <webElementGuid>87cc2e9a-8a9e-46cd-9144-76197e1faefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Display']</value>
      <webElementGuid>babeed8d-eabd-4611-896c-97d9c5c94614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
