<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CreditLimitAmount</name>
   <tag></tag>
   <elementGuidId>767abf7d-ebb8-4e0d-8e44-6b6ba3919cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CreditLimitAmount&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CreditLimitAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce0bed31-0ef5-478e-9da4-17edae703e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d737ab82-6049-457a-b7c1-5ea3ec63cb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>90ed222f-2c29-42bb-b866-8dc2e18b651f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CreditLimitAmount</value>
      <webElementGuid>aeee55c5-da6b-4b97-9ee2-3311f3d1707f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-edit align-right use-rtl ng-pristine ng-valid ng-isolate-scope ng-valid-decimalcheck ng-empty ng-valid-required ng-valid-maxlength ng-touched</value>
      <webElementGuid>415e46a1-91cb-4fb8-9046-cd8b8200b2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.maskValue</value>
      <webElementGuid>a29441e8-402a-4d09-9cc4-8bf1fc17e823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.toNumber(vm.maskValue)</value>
      <webElementGuid>c5d6a6a3-ea93-4e05-a440-4c71c493aae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-maxlength</name>
      <type>Main</type>
      <value>{{vm.maxLength}}</value>
      <webElementGuid>c3429ab0-bbc8-4464-b09e-13a9924e8577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-mask</name>
      <type>Main</type>
      <value>vm.maskConf</value>
      <webElementGuid>f2440b05-4353-4a96-8779-7ab2e2bc268d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>int-value</name>
      <type>Main</type>
      <value>vm.value[vm.field.code]</value>
      <webElementGuid>74810e54-ed44-4b8e-babb-7a68450ddadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>vm.req</value>
      <webElementGuid>37afe6e7-3be9-407f-8e86-2bf3ac67424c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>38b56a62-24f5-4d08-8671-ea536ba6c291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;body_ custom zoomed_del browser- theme-grey&quot;]/div[2]/layout-manager[@class=&quot;custom ng-isolate-scope&quot;]/div[@class=&quot;main-panel&quot;]/layout[@class=&quot;layout-frame ng-scope ng-isolate-scope active-frame&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;panel animate pane_ContractApplSetCreditLimit  label-warning id_10 last&quot;]/tab[@class=&quot;custom_tab_2 tab-container&quot;]/div[@class=&quot;tab has-sub-tab package-WSCards_APPLICATION_MANAGEMENT   tab-form&quot;]/div[@class=&quot;tab-content tab-without-links has-not-top-links&quot;]/div[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;form-container-outer&quot;]/form[@class=&quot;content-element ng-pristine vertical-layout ng-valid-decimalcheck ng-valid-maxlength ng-invalid ng-invalid-required ng-valid-check-spaces ng-valid-ui-select-required-validator&quot;]/div[@class=&quot;inner inner-x ng-scope hovered inner-visible&quot;]/div[@class=&quot;form-container form-sub&quot;]/div[@class=&quot;first-group ng-scope&quot;]/div[@class=&quot;field-block-container&quot;]/field-block[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-field field_code_CreditLimitAmount&quot;]/div[@class=&quot;form-value&quot;]/field[@class=&quot;field-value ng-isolate-scope&quot;]/decimal[@class=&quot;field ng-scope ng-isolate-scope&quot;]/input[@class=&quot;text-edit align-right use-rtl ng-pristine ng-valid ng-isolate-scope ng-valid-decimalcheck ng-empty ng-valid-required ng-valid-maxlength ng-touched&quot;]</value>
      <webElementGuid>f9ef4d4e-62c3-47c6-aab8-b810288ede97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CreditLimitAmount']</value>
      <webElementGuid>6014aa9c-b43c-470a-8a49-db8831468b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//decimal/input</value>
      <webElementGuid>9f005f14-7c7e-460f-bed9-2716bbb321ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'CreditLimitAmount']</value>
      <webElementGuid>e6906c27-581f-4f34-8604-167fc6cd5c7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
