<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_40664298107290</name>
   <tag></tag>
   <elementGuidId>bc12ee29-3cdf-4be6-9231-4ea9d3534c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gridElement']/div[5]/div/div/div[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slick-cell.l3.r3.active.selected > span.cell-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fc6e52e4-8d1c-4174-9b39-0d06562bfb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2b7a86ea-8674-4d7b-a384-9f3541a6bbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>40664298107290</value>
      <webElementGuid>6727cfb5-c079-4aad-8b6a-c5305d849f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell-content</value>
      <webElementGuid>e8e22cff-5650-46ed-809f-b3783f989247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>40664298107290</value>
      <webElementGuid>68726642-2c5b-464a-a167-844a12bdad49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridElement&quot;)/div[@class=&quot;slick-viewport&quot;]/div[@class=&quot;grid-canvas&quot;]/div[@class=&quot;ui-widget-content slick-row active selected even&quot;]/div[@class=&quot;slick-cell l3 r3 active selected&quot;]/span[@class=&quot;cell-content&quot;]</value>
      <webElementGuid>c5709491-f005-4574-80b5-5b7b78813a33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridElement']/div[5]/div/div/div[4]/span</value>
      <webElementGuid>d5d91d0f-f310-4b44-b6a4-b37390890487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AIW Jakarta 1'])[1]/following::span[6]</value>
      <webElementGuid>a0f4b2df-906f-4b7b-ae21-061d4aba7b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::span[3]</value>
      <webElementGuid>83de070f-881a-4c0c-a5cd-7b1fcda71535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instalment: Restructure'])[1]/preceding::span[6]</value>
      <webElementGuid>339ee5a6-40e2-4c92-adb5-d0e6a5a37019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='40664298107290']/parent::*</value>
      <webElementGuid>bccb1626-2137-43cd-bb43-c424d709a8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[4]/span</value>
      <webElementGuid>1e2e54e0-05e2-4922-9b24-c735bbe1af3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '40664298107290' and (text() = '40664298107290' or . = '40664298107290')]</value>
      <webElementGuid>428f4a2c-15d9-4ca0-adfb-68b8c459629c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
