<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_40663759706930</name>
   <tag></tag>
   <elementGuidId>79432841-861a-4477-83e8-30c08d0d7ebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div/div/div[5]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slick-cell.l4.r4.selected > span.cell-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>547a8f0f-8913-457d-a721-16037ce46bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>664d969e-5003-4a49-8cc4-b26729382d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>40663759706930</value>
      <webElementGuid>3978151e-a08f-430f-94dd-7bffdb91d524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell-content</value>
      <webElementGuid>a978e52f-2e78-45e2-8647-5d45532f80d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>40663759706930</value>
      <webElementGuid>ccf168a5-3a41-44bd-83c5-dbffc0f403d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridElement&quot;)/div[@class=&quot;slick-viewport&quot;]/div[@class=&quot;grid-canvas&quot;]/div[@class=&quot;ui-widget-content slick-row active selected even&quot;]/div[@class=&quot;slick-cell l4 r4 selected&quot;]/span[@class=&quot;cell-content&quot;]</value>
      <webElementGuid>ed2505ca-b908-4c33-851a-aa1a5fbf0b99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridElement']/div[5]/div/div/div[5]/span</value>
      <webElementGuid>3ee36222-ec80-418b-b540-d353740fc8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AIW Jakarta 1'])[1]/following::span[6]</value>
      <webElementGuid>5a624f52-2b24-429c-99b8-e985a824566a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issuing'])[1]/following::span[9]</value>
      <webElementGuid>e5612cee-5f0a-4f59-9b53-b8293716bc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A1690'])[1]/preceding::span[3]</value>
      <webElementGuid>90f5bac3-b8c0-4c2d-8675-5ab1a643d60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signer Step (MS)'])[1]/preceding::span[6]</value>
      <webElementGuid>a30f8d57-8d68-4393-a121-082d80c248bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='40663759706930']/parent::*</value>
      <webElementGuid>df18fdca-ac3f-43c8-b14b-eb2d2f81366a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[5]/span</value>
      <webElementGuid>d7395d54-ce1b-413e-a0ad-4b5ce59f325a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '40663759706930' and (text() = '40663759706930' or . = '40663759706930')]</value>
      <webElementGuid>27829177-31bf-4a0b-bfef-c193b5c2d4ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
