<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_product_002_corp</name>
   <tag></tag>
   <elementGuidId>f264a22c-cda7-4d18-8726-9e1d905724d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='002-Corporate Card 01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-field.field_code_Product.readonly > div.form-value > field.field-value.ng-isolate-scope > readonly-field.field.ng-scope.ng-isolate-scope > div.readonly-field-wrapper.readonly-field-wrapper--input.readonly-field-wrapper--inspectable > input.text-edit.ro.use-rtl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>501fa36f-e830-4d5f-9d96-57b38bf638b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.chooseHTMLTag() === 'input' &amp;&amp; !vm.isMultiselect()</value>
      <webElementGuid>ff07749f-c660-4b43-8e78-3121a2598d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d0b78e3-07b0-4148-a9d0-f3fb0d18e55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f132c0bb-9295-4145-b650-f168416c08a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-edit ro  use-rtl</value>
      <webElementGuid>76c08018-2e45-4a18-8436-5c70ccdefb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'align-right': ['number', 'int'].indexOf(field.type) != -1}</value>
      <webElementGuid>0582d0f0-3341-4737-adf8-a7fb652676c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-value</name>
      <type>Main</type>
      <value>vm.inputValue</value>
      <webElementGuid>332a2582-7a1d-4cbf-8ac4-b6ce5a3470ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>002-Corporate Card 01</value>
      <webElementGuid>5fbe7c6a-9636-4dc0-92c1-502852781752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>event.preventDefault()</value>
      <webElementGuid>7b0e4392-5f9f-4d14-a39c-24c5e7ce8f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d8c2cd1f-825f-40c5-9600-56cab73ea74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>002-Corporate Card 01</value>
      <webElementGuid>38712cb9-e9b9-4cc8-a2b4-0d99f46200c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;body_ custom zoomed_del browser- theme-grey&quot;]/div[2]/layout-manager[@class=&quot;custom ng-isolate-scope&quot;]/div[@class=&quot;main-panel&quot;]/layout[@class=&quot;layout-frame ng-scope ng-isolate-scope active-frame&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;panel animate pane_ContractApplSubtreeApplicationDetails   id_10 last&quot;]/tab[@class=&quot;custom_tab_1 tab-container&quot;]/div[@class=&quot;tab has-sub-tab package-WSCards_APPLICATION_MANAGEMENT   tab-form&quot;]/div[@class=&quot;tab-content has-not-top-links&quot;]/div[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;form-container-outer&quot;]/form[@class=&quot;content-element ng-pristine ng-valid readonly vertical-layout&quot;]/div[@class=&quot;inner inner-x ng-scope hovered inner-visible&quot;]/div[@class=&quot;form-container form-sub&quot;]/div[@class=&quot;first-group ng-scope&quot;]/div[@class=&quot;field-block-container&quot;]/field-block[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-field field_code_Product readonly&quot;]/div[@class=&quot;form-value&quot;]/field[@class=&quot;field-value ng-isolate-scope&quot;]/readonly-field[@class=&quot;field ng-scope ng-isolate-scope&quot;]/div[@class=&quot;readonly-field-wrapper readonly-field-wrapper--input readonly-field-wrapper--inspectable&quot;]/input[@class=&quot;text-edit ro  use-rtl&quot;]</value>
      <webElementGuid>b24ddc60-d3a2-4e18-a7f3-20b632925d72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='002-Corporate Card 01']</value>
      <webElementGuid>f4d6a3a6-99e8-4815-b7d8-fb3ada8eb626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/field-block/div/div[2]/field/readonly-field/div/input</value>
      <webElementGuid>fc2006dc-856b-4560-814c-43faa470ed44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = '002-Corporate Card 01']</value>
      <webElementGuid>7a7a83ad-eb63-4f45-b691-4e146430bffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
