<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>582eeae7-9289-458f-9c2a-89ce4a5be433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.form-save-bar-button.invalid-btn.ng-binding.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ca636ef-216e-4fb0-bcca-6c27dd07a948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-save-bar-button invalid-btn ng-binding ng-scope</value>
      <webElementGuid>df7fac37-0dba-4e9f-a30e-135372f338ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>focusOnBadField()</value>
      <webElementGuid>960e120f-e792-4a5b-a9bb-3cf253967aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-enter</name>
      <type>Main</type>
      <value>focusOnBadField()</value>
      <webElementGuid>84b2f9e8-ab3d-4862-9209-356336af7abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!checkAutoSaveValue() &amp;&amp; (!loading &amp;&amp; !(readonly || is_search)) &amp;&amp; getForm().$invalid</value>
      <webElementGuid>cdf54bd5-abbf-4972-ab0f-85d4dca91296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Save
  </value>
      <webElementGuid>cdf3421c-afab-48de-bee3-d7e79d5a099a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;body_ custom zoomed_del browser- theme-grey&quot;]/div[2]/layout-manager[@class=&quot;custom ng-isolate-scope&quot;]/div[@class=&quot;main-panel&quot;]/layout[@class=&quot;layout-frame ng-scope ng-isolate-scope active-frame&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;panel animate pane_NodeApplAddressListAddressLimitedEdit  label-warning id_41 last first&quot;]/tab[@class=&quot;custom_tab_0 tab-container&quot;]/div[@class=&quot;tab has-sub-tab package-WSCards_APPLICATION_MANAGEMENT   tab-form&quot;]/div[@class=&quot;tab-content tab-without-links has-not-top-links&quot;]/div[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;form-container-outer&quot;]/save-bar[@class=&quot;save-bar ng-scope vertical&quot;]/div[@class=&quot;form-save-bar&quot;]/button[@class=&quot;form-save-bar-button invalid-btn ng-binding ng-scope&quot;]</value>
      <webElementGuid>3ae06fe2-2eb7-45d7-8314-3762377da565</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::button[1]</value>
      <webElementGuid>3ed4917c-4691-4f70-ab5f-83616315f733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::button[2]</value>
      <webElementGuid>8281ef51-fcdc-4cd3-a53d-2588d2ea8658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>4dd59f69-6271-4348-a430-88c90f77b326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>0b31454d-f2eb-4b30-b7f9-7b2b3b0fb591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
    Save
  ' or . = '
    Save
  ')]</value>
      <webElementGuid>b2d6b561-aa39-4b49-9728-47fdb860e0af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
