<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_option_value</name>
   <tag></tag>
   <elementGuidId>d7698b18-4998-478f-a8ca-597171d1aafa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-select-choices-row-9-1']/span/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'ng-binding ng-scope' and (text() = '${pilih_value}' or . = '${pilih_value}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-select-choices-row-9-1 > span.ui-select-choices-row-inner > span.ng-binding.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5ac406c8-fb01-47be-82fc-546abfb43181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>''+ ctrl.escapeSpecSymbols(dataItem.value) | highlight: $select.search</value>
      <webElementGuid>175fae7d-4026-4a3c-9e61-ead5aef8a5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
      <webElementGuid>2e7a218e-7d33-4775-b32c-0da3b44a3b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${pilih_value}</value>
      <webElementGuid>24cae000-e4e3-4d15-b29c-9f1771ae46ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-select-choices-row-9-1&quot;)/span[@class=&quot;ui-select-choices-row-inner&quot;]/span[@class=&quot;ng-binding ng-scope&quot;]</value>
      <webElementGuid>7dd6e7c5-7ba7-4045-824e-ab77d6899207</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-select-choices-row-9-1']/span/span</value>
      <webElementGuid>158bc192-0722-4294-b803-a14905328bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Physical'])[3]/following::span[2]</value>
      <webElementGuid>d686803e-9a43-48e1-a97f-6953fcb098b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Physical'])[2]/following::span[7]</value>
      <webElementGuid>749dd2d5-08ce-479b-a05d-17b774dcc9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empty'])[1]/preceding::span[1]</value>
      <webElementGuid>13ef3244-daf6-41b3-885e-40330718cf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='loading...'])[1]/preceding::span[2]</value>
      <webElementGuid>8bca1e84-44a2-4d0e-af4a-5c21c68b1936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Virtual']/parent::*</value>
      <webElementGuid>f2d60bd2-cf41-4e6c-82ba-fcbf048d0d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[4]/span/span</value>
      <webElementGuid>655fffb5-b861-48c9-aefd-e7753a751c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Virtual' or . = 'Virtual')]</value>
      <webElementGuid>c98982aa-67d5-4115-9788-33452a6cfc48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
