<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PAN_LAST_DIGITS</name>
   <tag></tag>
   <elementGuidId>959fbbf1-9063-4145-8700-eeb7407788a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='PAN_LAST_DIGITS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;PAN_LAST_DIGITS&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21d8f08b-a5ce-405f-8ff5-4c509603b782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6411808d-88f9-44b9-98db-1b68341063ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b1d32b5d-a465-4b7d-81ef-a86d02d77da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-edit use-rtl ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-check-spaces</value>
      <webElementGuid>026f8295-a845-4a9f-8a63-0062c0eb2800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'align-right': isNumber}</value>
      <webElementGuid>dcae26bf-c936-4a60-b9f9-d8879b1827fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PAN_LAST_DIGITS</value>
      <webElementGuid>ddd13fd1-1b86-4d01-8641-7ab8b0841ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model.masked_value</value>
      <webElementGuid>2dafb127-5005-4b73-b99e-6b75eebdb6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>req</value>
      <webElementGuid>66c64fae-a49f-40e3-b837-51ad28f1c767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c9ef106c-b017-4094-a395-9e4262ff5d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-maxlength</name>
      <type>Main</type>
      <value>{{maxLength}}</value>
      <webElementGuid>816dec38-cf75-4b45-b8c8-4b04cefa49a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-trim</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fae6edcc-cfa2-4ee0-a2a4-15b6a7b26b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>applyChanges()</value>
      <webElementGuid>9217ef0a-877a-41bb-815d-36fcd088a2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>applyChanges()</value>
      <webElementGuid>2881891e-42f9-4b6e-bf1a-5875331bcd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>1314cae1-aa26-4011-b6f5-b1cd3e36bdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>182658c4-7db9-485c-896b-49e6a29dcc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;body_ custom zoomed_del browser- theme-grey&quot;]/div[2]/layout-manager[@class=&quot;custom ng-isolate-scope&quot;]/div[@class=&quot;main-panel&quot;]/layout[@class=&quot;layout-frame ng-scope ng-isolate-scope active-frame&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;panel animate pane_Apply   id_11 last first&quot;]/tab[@class=&quot;custom_tab_0 tab-container&quot;]/div[@class=&quot;tab has-sub-tab package-CSWBRI&quot;]/div[@class=&quot;query-form-wrapper&quot;]/div[@class=&quot;query-form-container ng-scope hovered&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;query-form&quot;]/form[@class=&quot;content-element ng-pristine vertical-layout ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-check-spaces&quot;]/div[@class=&quot;form-container form-field-count-2&quot;]/field-block[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-field field_code_PAN_LAST_DIGITS required&quot;]/div[@class=&quot;form-value&quot;]/field[@class=&quot;field-value ng-isolate-scope&quot;]/text-field[@class=&quot;field ng-scope ng-isolate-scope&quot;]/input[@class=&quot;text-edit use-rtl ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-check-spaces&quot;]</value>
      <webElementGuid>58aede7b-7b9b-415b-8998-639946d2dd79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='PAN_LAST_DIGITS']</value>
      <webElementGuid>ffc09e73-5d29-4d26-9f52-49e0b5c3890f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//field-block[2]/div/div[2]/field/text-field/input</value>
      <webElementGuid>7f7c39e0-8b1d-4e2d-8ab7-c3abef3d222d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'PAN_LAST_DIGITS']</value>
      <webElementGuid>6d4d8aff-b5b8-477e-9148-92610cf9cef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
