<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_cl_mkr_2</name>
   <tag></tag>
   <elementGuidId>dc0e6eb3-6de1-475d-95e7-3ff89bd22a2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slick-cell.l10.r10.active.selected > span.cell-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gridElement']/div[5]/div/div/div[11]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f412d442-7fd2-4050-af38-e51b09b7496a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c29148da-70ab-4aa5-8b5e-13413c1ec6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>cl_mkr_2</value>
      <webElementGuid>e146efa2-687b-4a5b-bd38-59def1cf59c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell-content</value>
      <webElementGuid>4568c080-02cc-464c-882c-becc4d6e35c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cl_mkr_2</value>
      <webElementGuid>4dd73daa-7084-450c-9aa5-57fd8845bd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridElement&quot;)/div[@class=&quot;slick-viewport&quot;]/div[@class=&quot;grid-canvas&quot;]/div[@class=&quot;ui-widget-content slick-row active selected even&quot;]/div[@class=&quot;slick-cell l10 r10 active selected&quot;]/span[@class=&quot;cell-content&quot;]</value>
      <webElementGuid>41557888-dd2f-4a07-a3e1-e936fee8aa42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridElement']/div[5]/div/div/div[11]/span</value>
      <webElementGuid>d3ff2df9-2ff0-443e-98c4-879c2d7cea40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cl_mkr_2'])[2]/following::span[3]</value>
      <webElementGuid>a6102f51-05c1-4047-8ee6-8b373b429fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Entry'])[1]/following::span[6]</value>
      <webElementGuid>bc4073a0-e03c-4530-a5a8-df8612f83e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loaded'])[1]/preceding::span[3]</value>
      <webElementGuid>811f7fbd-00b3-45c8-a5a5-19762c92ab6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting'])[1]/preceding::span[6]</value>
      <webElementGuid>01b81429-1ad1-4eb4-a219-7a0401a3fd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[11]/span</value>
      <webElementGuid>54c0a563-2261-421c-9400-b727a4d24a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'cl_mkr_2' and (text() = 'cl_mkr_2' or . = 'cl_mkr_2')]</value>
      <webElementGuid>9bd8dadc-695f-4e3c-bc2a-def5b6027594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
