<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__text-edit ro  use-rtl</name>
   <tag></tag>
   <elementGuidId>3f24a645-e830-4333-bb56-57d9c1d1e148</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='002-C-ACCT2724149779630848']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-field.field_code_CONTRACT_NUMBER.readonly > div.form-value > field.field-value.ng-isolate-scope > readonly-field.field.ng-scope.ng-isolate-scope > div.readonly-field-wrapper.readonly-field-wrapper--input.readonly-field-wrapper--inspectable > input.text-edit.ro.use-rtl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a397f066-873e-4e4d-b78e-4e3d1f888704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.chooseHTMLTag() === 'input' &amp;&amp; !vm.isMultiselect()</value>
      <webElementGuid>d53ae4c7-ff70-407a-bec1-a26126b9073f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bc1b8b2-4824-4980-8b4f-09ab2ebc3da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3eb52ed1-15fe-4094-bf52-106853821301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-edit ro  use-rtl</value>
      <webElementGuid>85571e7d-c7e4-42d0-88bb-c3b76d3c1f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'align-right': ['number', 'int'].indexOf(field.type) != -1}</value>
      <webElementGuid>842b0403-ceb9-436a-bf1a-164c369df751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-value</name>
      <type>Main</type>
      <value>vm.inputValue</value>
      <webElementGuid>17d236a6-d542-4865-a1fe-ba70adafbedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>002-C-ACCT2724149779630848</value>
      <webElementGuid>b024ea70-c5c8-49e1-9b08-1534b7dfd6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>event.preventDefault()</value>
      <webElementGuid>9e09167e-a0fe-4ef3-b1be-f59f72e51461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>38b2640a-881b-4503-9c67-ca7f7f7cfe8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>002-C-ACCT2724149779630848</value>
      <webElementGuid>aac052af-ac94-4ad2-9d3b-12b63b8f3244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;body_ custom zoomed_del browser- theme-grey&quot;]/div[2]/layout-manager[@class=&quot;custom ng-isolate-scope&quot;]/div[@class=&quot;main-panel&quot;]/layout[@class=&quot;layout-frame ng-scope ng-isolate-scope active-frame&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;panel animate pane_CSWBRI_CSW_Express_GetDetails__ACC_CONTRACT   id_5 last&quot;]/tab[@class=&quot;custom_tab_1 tab-container&quot;]/div[@class=&quot;tab has-sub-tab package-CSWBRI   tab-form&quot;]/div[@class=&quot;tab-content tab-without-links has-top-links&quot;]/div[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;form-container-outer&quot;]/form[@class=&quot;content-element ng-pristine ng-valid readonly vertical-layout&quot;]/div[@class=&quot;inner inner-x ng-scope hovered inner-visible&quot;]/div[@class=&quot;form-container form-sub&quot;]/div[@class=&quot;first-group ng-scope&quot;]/div[@class=&quot;field-block-container&quot;]/field-block[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-field field_code_CONTRACT_NUMBER readonly&quot;]/div[@class=&quot;form-value&quot;]/field[@class=&quot;field-value ng-isolate-scope&quot;]/readonly-field[@class=&quot;field ng-scope ng-isolate-scope&quot;]/div[@class=&quot;readonly-field-wrapper readonly-field-wrapper--input readonly-field-wrapper--inspectable&quot;]/input[@class=&quot;text-edit ro  use-rtl&quot;]</value>
      <webElementGuid>19283688-f177-4868-bd27-ff3058cb11ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='002-C-ACCT2724149779630848']</value>
      <webElementGuid>984bfa91-3579-45ac-8d9f-0c3ecfa3d802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/field-block/div/div[2]/field/readonly-field/div/input</value>
      <webElementGuid>f5de4c35-73ba-413f-b626-32728eb421e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = '002-C-ACCT2724149779630848']</value>
      <webElementGuid>0f1b0a16-ecde-4cb8-a280-c815ebcfd7f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
