<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_002-C-ACCT2724149779630848</name>
   <tag></tag>
   <elementGuidId>09ec8c48-6eb0-4ead-bfee-96cd144f0cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div/div[1]/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slick-cell.l1.r1.active.selected > span.cell-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7c8dd70-3cf4-4f90-a800-530547c7773f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9cb63376-5804-40b9-9733-aa5678bc4f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>002-C-ACCT2724149779630848</value>
      <webElementGuid>01d003fa-5207-4433-816b-e4dd0799a1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell-content</value>
      <webElementGuid>0d1db4d4-1269-42ba-8b60-57ac579f9eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>002-C-ACCT2724149779630848</value>
      <webElementGuid>8bdf5098-09af-4069-9d43-02f6f8d2a35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridElement&quot;)/div[@class=&quot;slick-viewport&quot;]/div[@class=&quot;grid-canvas&quot;]/div[@class=&quot;ui-widget-content slick-row active selected even&quot;]/div[@class=&quot;slick-cell l1 r1 active selected&quot;]/span[@class=&quot;cell-content&quot;]</value>
      <webElementGuid>7d3aab46-5f08-46de-ae46-6eed0bdb8e93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridElement']/div[5]/div/div/div[2]/span</value>
      <webElementGuid>1851eca2-de28-4650-ad78-9ef48fd490c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account OK'])[1]/preceding::span[7]</value>
      <webElementGuid>623a8eed-096b-4a8f-a19b-cc8c911602f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ini sudah diedit aldy'])[1]/preceding::span[16]</value>
      <webElementGuid>69651701-69c2-42f7-a83e-a0f12c26c67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='002-C-ACCT2724149779630848']/parent::*</value>
      <webElementGuid>337f20a4-25b0-4a36-844d-23c6b7d7983c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/span</value>
      <webElementGuid>3fa62e73-444e-4912-bedc-cb780a08ec81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '002-C-ACCT2724149779630848' and (text() = '002-C-ACCT2724149779630848' or . = '002-C-ACCT2724149779630848')]</value>
      <webElementGuid>5b162992-df79-4a1f-89ed-fda2685eedff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
