<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_By Card</name>
   <tag></tag>
   <elementGuidId>3c25aeb8-6a40-419f-87bb-307d8459fdb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='query-bar']/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6304d752-9546-4163-8ae9-8b1f09ed662c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getTitleForQuery(header)   | sanitize</value>
      <webElementGuid>3d4e1d58-3d97-40be-9091-1e2826263285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>73e2b452-c461-4ef5-98f4-6d630c577714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>By Card</value>
      <webElementGuid>9e7ef028-f1a6-4f50-8905-31d77e60ed3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;query-bar&quot;)/div[@class=&quot;tab-label label-link-group br-step step-hide step-hide tab-query ng-scope&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>73bcf6a8-f694-4cb2-9fd1-1ccf56655e4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='query-bar']/div[3]/span</value>
      <webElementGuid>e5a733ad-0281-4147-a15f-c22913ed9cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By KTP'])[1]/following::span[1]</value>
      <webElementGuid>8b2db202-3569-4050-b165-0f0f11bdf78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Name'])[1]/following::span[3]</value>
      <webElementGuid>5f9f219e-f7e7-441d-ad49-478b8c2fb87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Phone'])[1]/preceding::span[1]</value>
      <webElementGuid>25141e8c-4556-4ea8-a97a-91a14a7897d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Name &amp; Card'])[1]/preceding::span[2]</value>
      <webElementGuid>e613a56f-781f-4c50-87ef-8383e5f46326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='By Card']/parent::*</value>
      <webElementGuid>65ca72b0-f2f5-456d-a25b-557cae633d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/ng-transclude/div/div/div[3]/span</value>
      <webElementGuid>eece93cf-6e85-4d53-ac7b-6b4cecb0ae17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'By Card' or . = 'By Card')]</value>
      <webElementGuid>5cf49c20-01d9-4966-adcd-d7307c3c5583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
